"""Dependency reproducibility audit: real repo passes, decay fails."""
from __future__ import annotations

from pathlib import Path

from scripts import audit_dependency_reproducibility as repro


def test_real_repo_passes():
    assert repro.audit_all() == []


def test_lockfile_exists_with_hashes_for_every_pin():
    lock = Path(repro._REPO_ROOT) / repro.LOCKFILE
    assert lock.exists()
    text = lock.read_text(encoding="utf-8")
    assert text.count("--hash=sha256:") > 500  # full tree, not a stub
    assert "pip-compile" in text  # provenance header


def test_every_declared_requirement_is_locked():
    declared = repro.top_level_requirements()
    assert "pytest" in declared and "streamlit" in declared
    assert not [
        v for v in repro.audit_python_lock() if "stale" in v
    ]


def test_missing_lock_fails(tmp_path):
    (tmp_path / "requirements.txt").write_text("requests>=2\n", encoding="utf-8")
    violations = repro.audit_python_lock(tmp_path)
    assert any("missing" in v for v in violations)


def test_hashless_pin_fails(tmp_path):
    (tmp_path / "requirements.txt").write_text("requests>=2\n", encoding="utf-8")
    (tmp_path / repro.LOCKFILE).write_text(
        "# generated by pip-compile\nrequests==2.32.0\n", encoding="utf-8"
    )
    violations = repro.audit_python_lock(tmp_path)
    assert any("without a sha256 hash" in v for v in violations)


def test_stale_lock_fails(tmp_path):
    (tmp_path / "requirements.txt").write_text(
        "requests>=2\nbrand-new-dep>=1\n", encoding="utf-8"
    )
    (tmp_path / repro.LOCKFILE).write_text(
        "requests==2.32.0 \\\n    --hash=sha256:" + "a" * 64 + "\n",
        encoding="utf-8",
    )
    violations = repro.audit_python_lock(tmp_path)
    assert any("brand-new-dep" in v and "stale" in v for v in violations)


def test_npm_install_in_workflow_fails(tmp_path):
    wf = tmp_path / "ci.yml"
    wf.write_text(
        "jobs:\n  build:\n    steps:\n      - run: npm install\n",
        encoding="utf-8",
    )
    violations = repro.audit_workflows(tmp_path)
    assert any("npm ci" in v for v in violations)


def test_npm_ci_in_workflow_passes(tmp_path):
    wf = tmp_path / "ci.yml"
    wf.write_text(
        "jobs:\n  build:\n    steps:\n      - run: npm ci --omit=dev\n",
        encoding="utf-8",
    )
    assert repro.audit_workflows(tmp_path) == []


def test_python_version_policy_divergence_fails(tmp_path):
    wf = tmp_path / "ci.yml"
    wf.write_text(
        'jobs:\n  t:\n    steps:\n      - uses: x\n'
        '        with:\n          python-version: "3.12"\n',
        encoding="utf-8",
    )
    violations = repro.audit_workflows(tmp_path)
    assert any("3.12" in v for v in violations)
