"""Canonical holdings truth gate for the risk engine.

Close-the-Loop sprint (2026-07-04).  Forensic-audit findings SP-001/005/009/
010/011/012: the only stop/TP monitoring in the system read the demoted
``moltbook/open_positions.json`` phantom ledger while the file the project
itself declares "the only canonical truth for OPEN positions"
(``data/daily_payload/verified_current_holdings.json``) was consumed by
nothing, carried no stop fields, and had no freshness gate.

This module is that gate.  It is the ONLY sanctioned way for risk/action
machinery to obtain active positions:

* **Freshness fail-closed** — ``run_date`` older than ``max_age_days``
  (default 3) yields ``HOLDINGS_TRUTH_STALE``; missing/invalid file yields
  ``HOLDINGS_TRUTH_MISSING`` / ``HOLDINGS_TRUTH_INVALID``.  A non-OK status
  returns ZERO monitorable positions — stale truth must never silently feed
  stop-breach math.
* **Stop discipline fail-closed** — a position without a numeric
  ``stop_loss`` is returned as ``BLOCKED_MISSING_STOP`` and excluded from
  monitorable positions.  No stop, no "healthy".
* **Leverage explicit** — ``leverage`` is surfaced on every row; a leveraged
  position missing its stop escalates to ``BLOCKED_MISSING_STOP_LEVERAGED``
  (severity CRITICAL).  4x INR names can never be treated as quiet 1x risk.
* **Price honesty** — ``current_price`` is attached only from ingested
  ``market_data`` bars with a ``price_as_of`` timestamp; a missing or stale
  bar (older than ``max_price_age_days``) blocks monitoring with
  ``BLOCKED_STALE_PRICE`` / ``BLOCKED_NO_PRICE`` instead of evaluating stops
  against fiction.

Advisory-only: this module reads files and the local DB.  It never places,
sizes, or executes anything.
"""
from __future__ import annotations

import argparse
import json
import os
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Sequence

try:  # package layout
    from scripts import persistence
    from scripts.advisory_contract import advisory_safety_stamps
    from scripts.runtime_common import REPO_ROOT
except ModuleNotFoundError:  # pragma: no cover - flat-layout fallback
    import persistence  # type: ignore[no-redef]
    from advisory_contract import advisory_safety_stamps  # type: ignore[no-redef]
    from runtime_common import REPO_ROOT  # type: ignore[no-redef]

HOLDINGS_TRUTH_PATH = REPO_ROOT / "data" / "daily_payload" / "verified_current_holdings.json"
ENV_PATH_OVERRIDE = "HOLDINGS_TRUTH_PATH"

DEFAULT_MAX_AGE_DAYS = 3.0
DEFAULT_MAX_PRICE_AGE_DAYS = 3.0

STATUS_OK = "OK"
STATUS_STALE = "HOLDINGS_TRUTH_STALE"
STATUS_MISSING = "HOLDINGS_TRUTH_MISSING"
STATUS_INVALID = "HOLDINGS_TRUTH_INVALID"

MON_READY = "READY"
MON_MISSING_STOP = "BLOCKED_MISSING_STOP"
MON_MISSING_STOP_LEV = "BLOCKED_MISSING_STOP_LEVERAGED"
MON_UNCONFIRMED_STOP = "BLOCKED_UNCONFIRMED_STOP"
MON_INVALID_STOP = "BLOCKED_INVALID_STOP"
MON_NO_PRICE = "BLOCKED_NO_PRICE"
MON_STALE_PRICE = "BLOCKED_STALE_PRICE"

SOURCE_NAME = "verified_current_holdings"

# Feed-the-Loop sprint (2026-07-04): stop-confirmation contract.  A stop is
# only USABLE for risk monitoring when the operator has confirmed it — a
# numeric value alone is not truth.  Suggested stops generated by
# --write-template carry stop_loss_source="policy_suggested" and
# stop_loss_confirmed=false and therefore BLOCK until confirmed.
CONFIRMED_STOP_SOURCES = frozenset(
    {"operator", "policy_confirmed", "sheet_import_confirmed"}
)

# Open-the-Gate sprint (2026-07-04): stop activation additionally requires an
# explicit, typed operator acknowledgement.  The exact text below must appear
# in the template — an agent or script can never produce it "by accident".
OPERATOR_ACK_TEXT = "I_CONFIRM_THESE_STOPS_ARE_MY_OPERATOR_RISK_LIMITS"

CONFIRMATION_REQUIRED_JSON = (
    REPO_ROOT / "data" / "daily_payload"
    / "stop_loss_operator_confirmation_required.json"
)
CONFIRMATION_REQUIRED_MD = REPO_ROOT / "STOP_LOSS_CONFIRMATION_REQUIRED.md"
HOLDINGS_ARCHIVE_DIR = REPO_ROOT / "data" / "daily_payload" / "archive"

# Freshness three-tier gate (minutes).
FRESHNESS_FRESH_MAX_MIN = 1440.0      # <= 1 day  -> FRESH
FRESHNESS_DEGRADED_MAX_MIN = 4320.0   # <= 3 days -> DEGRADED
FRESH_FRESH = "FRESH"
FRESH_DEGRADED = "DEGRADED"
FRESH_BLOCKED = "BLOCKED"

# Deterministic suggested-stop policy (SUGGESTIONS ONLY — never activated
# without operator confirmation): 5% hard stop for 1x positions, 2.5% for
# leveraged positions (tighter price stop ≈ comparable capital-at-risk once
# leverage multiplies the move).
HARD_STOP_PCT_DEFAULT = 0.05
HARD_STOP_PCT_LEVERAGED = 0.025

STOP_TEMPLATE_PATH = (
    REPO_ROOT / "data" / "daily_payload" / "stop_loss_backfill_template.json"
)

OP_HEALTHY = "HEALTHY"
OP_DEGRADED = "DEGRADED"
OP_BLOCKED = "BLOCKED"
OP_BROKEN = "BROKEN"


def _parse_date(value: Any) -> datetime | None:
    if not value:
        return None
    text = str(value).strip()
    for fmt in ("%Y-%m-%dT%H:%M:%S%z", "%Y-%m-%dT%H:%M:%SZ", "%Y-%m-%d"):
        try:
            dt = datetime.strptime(text.replace("+00:00", "Z"), fmt)
        except ValueError:
            continue
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt
    return None


def _num(value: Any) -> float | None:
    if isinstance(value, bool) or value is None:
        return None
    try:
        f = float(value)
    except (TypeError, ValueError):
        return None
    return f


def _latest_prices(db_path: Any, symbols: set[str]) -> dict[str, tuple[str, float]]:
    """Latest real close per symbol from ingested market_data bars."""
    out: dict[str, tuple[str, float]] = {}
    if not symbols:
        return out
    try:
        conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    except sqlite3.Error:
        return out
    try:
        rows = conn.execute(
            "SELECT raw_payload FROM signal_events WHERE source_name = 'market_data'"
        ).fetchall()
    except sqlite3.Error:
        return out
    finally:
        conn.close()
    for (raw,) in rows:
        try:
            p = json.loads(raw)
        except (TypeError, json.JSONDecodeError):
            continue
        sym = str(p.get("symbol") or "").upper()
        if sym not in symbols:
            continue
        ts = str(p.get("timestamp") or "")
        close = _num(p.get("close")) or _num(p.get("latest_price"))
        if not ts or close is None or close <= 0:
            continue
        prev = out.get(sym)
        if prev is None or ts > prev[0]:
            out[sym] = (ts, close)
    return out


def load_holdings_truth_gate(
    *,
    path: Any = None,
    db_path: Any = None,
    now_utc: datetime | None = None,
    max_age_days: float = DEFAULT_MAX_AGE_DAYS,
    max_price_age_days: float = DEFAULT_MAX_PRICE_AGE_DAYS,
    attach_prices: bool = True,
) -> dict[str, Any]:
    """Load, validate, and freshness-gate the canonical holdings truth."""
    now = now_utc or datetime.now(timezone.utc)
    target = Path(
        path
        if path is not None
        else os.environ.get(ENV_PATH_OVERRIDE) or HOLDINGS_TRUTH_PATH
    )
    db = db_path if db_path is not None else persistence.DB_PATH

    gate: dict[str, Any] = {
        "report": "holdings_truth_gate",
        "source": SOURCE_NAME,
        "path": str(target),
        "checked_at_utc": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "max_age_days": max_age_days,
        "status": STATUS_OK,
        "run_date": None,
        "age_days": None,
        "holdings_age_minutes": None,
        "freshness_state": FRESH_BLOCKED,
        "canonical_holding_count": 0,
        "monitorable_position_count": 0,
        "missing_stop_count": 0,
        "unconfirmed_stop_count": 0,
        "leveraged_position_count": 0,
        "leveraged_without_stop_count": 0,
        "broker_confirmed_count": 0,
        "portfolio_stop_exposure": None,
        "portfolio_equity_basis": None,
        "portfolio_stop_exposure_fraction": None,
        "operational_state": OP_BROKEN,
        "risk_engine_ready": False,
        "positions": [],
        "blocked_positions": [],
        "issues": [],
        **advisory_safety_stamps(),
    }

    if not target.exists():
        gate["status"] = STATUS_MISSING
        gate["issues"].append(f"holdings truth file missing: {target}")
        return gate
    try:
        payload = json.loads(target.read_text(encoding="utf-8"))
        positions_raw = payload["positions"]
        assert isinstance(positions_raw, list)
    except Exception as exc:  # noqa: BLE001 - disclosed as INVALID
        gate["status"] = STATUS_INVALID
        gate["issues"].append(f"holdings truth unreadable: {type(exc).__name__}")
        return gate

    run_date = _parse_date(payload.get("run_date"))
    gate["run_date"] = payload.get("run_date")
    if run_date is None:
        gate["status"] = STATUS_INVALID
        gate["issues"].append("holdings truth has no parseable run_date")
        return gate
    age_days = (now - run_date).total_seconds() / 86400.0
    gate["age_days"] = round(age_days, 2)
    age_minutes = age_days * 1440.0
    gate["holdings_age_minutes"] = round(age_minutes, 1)
    gate["freshness_state"] = (
        FRESH_FRESH if age_minutes <= FRESHNESS_FRESH_MAX_MIN
        else FRESH_DEGRADED if age_minutes <= FRESHNESS_DEGRADED_MAX_MIN
        else FRESH_BLOCKED
    )
    if age_days > max_age_days:
        gate["status"] = STATUS_STALE
        gate["issues"].append(
            f"HOLDINGS_TRUTH_STALE: run_date {payload.get('run_date')} is "
            f"{age_days:.1f} days old (max {max_age_days:g}); all position "
            "management is demoted to review-only until the operator "
            "re-verifies holdings"
        )

    open_rows = [
        r for r in positions_raw
        if isinstance(r, dict) and str(r.get("status", "OPEN")).upper() == "OPEN"
    ]
    gate["canonical_holding_count"] = len(open_rows)

    symbols = {
        str(r.get("normalized_ticker") or r.get("ticker") or "").upper()
        for r in open_rows
    }
    prices = _latest_prices(db, symbols) if attach_prices else {}

    for row in open_rows:
        display = str(row.get("ticker") or "").upper()
        symbol = str(row.get("normalized_ticker") or display).upper()
        leverage = _num(row.get("leverage")) or 1.0
        stop_loss = _num(row.get("stop_loss"))
        take_profit = _num(row.get("take_profit"))
        entry_price = _num(row.get("entry_price"))
        price = prices.get(symbol)
        price_as_of, current_price = (price if price else (None, None))
        price_age_days = None
        if price_as_of:
            price_dt = _parse_date(price_as_of)
            if price_dt is not None:
                price_age_days = (now - price_dt).total_seconds() / 86400.0

        quantity = _num(row.get("quantity"))
        stop_source = row.get("stop_loss_source")
        stop_confirmed = bool(row.get("stop_loss_confirmed", False))
        stop_confirmed_at = row.get("stop_loss_confirmed_at")
        stop_updated_at = row.get("stop_loss_updated_at")
        leverage_ack = bool(row.get("leverage_risk_acknowledged", False))
        stop_usable = (
            stop_loss is not None
            and stop_confirmed
            and bool(stop_confirmed_at)
            and str(stop_source or "") in CONFIRMED_STOP_SOURCES
            # Open-the-Gate: a leveraged position's stop is only usable with
            # an explicit leverage-risk acknowledgement on the position.
            and (leverage <= 1 or leverage_ack)
        )
        stop_directionally_valid = (
            stop_loss is not None
            and entry_price is not None
            and 0 < stop_loss < entry_price  # long-only book today
        )
        # Loss_At_Stop = max(0, entry - stop) x quantity x leverage (long).
        loss_at_stop = None
        if stop_loss is not None and entry_price and quantity:
            loss_at_stop = max(0.0, entry_price - stop_loss) * quantity * leverage

        blocks: list[str] = []
        if stop_loss is None:
            blocks.append(
                MON_MISSING_STOP_LEV if leverage > 1 else MON_MISSING_STOP
            )
        elif not stop_directionally_valid:
            blocks.append(MON_INVALID_STOP)
        elif not stop_usable:
            blocks.append(MON_UNCONFIRMED_STOP)
        if current_price is None:
            blocks.append(MON_NO_PRICE)
        elif price_age_days is not None and price_age_days > max_price_age_days:
            blocks.append(MON_STALE_PRICE)

        norm = {
            "ticker": display,
            "symbol": symbol,
            "asset_name": row.get("asset_name"),
            "quantity": quantity,
            "entry_price": entry_price,
            "entry_timestamp": row.get("opened_at"),
            "stop_loss": stop_loss,
            "stop_loss_source": stop_source,
            "stop_loss_confirmed": stop_confirmed,
            "stop_loss_confirmed_at": stop_confirmed_at,
            "stop_loss_updated_at": stop_updated_at,
            "stop_usable": stop_usable,
            "leverage_risk_acknowledged": leverage_ack,
            "loss_at_stop": (
                round(loss_at_stop, 4) if loss_at_stop is not None else None
            ),
            "take_profit": take_profit,
            "invalidation_level": _num(row.get("invalidation_level")),
            "leverage": leverage,
            "currency": row.get("currency"),
            "current_price": current_price,
            "price_as_of": price_as_of,
            "price_age_days": (
                round(price_age_days, 2) if price_age_days is not None else None
            ),
            "broker_confirmed": bool(row.get("broker_confirmed", False)),
            "human_confirmed": bool(row.get("human_confirmed", False)),
            "source": SOURCE_NAME,
            "provenance": row.get("created_via"),
            "freshness_timestamp": payload.get("run_date"),
            "risk_monitoring": MON_READY if not blocks else blocks[0],
            "risk_monitoring_blocks": blocks,
        }
        if leverage > 1:
            gate["leveraged_position_count"] += 1
            if not stop_usable:
                gate["leveraged_without_stop_count"] += 1
        if stop_loss is None:
            gate["missing_stop_count"] += 1
        elif not stop_usable or not stop_directionally_valid:
            gate["unconfirmed_stop_count"] += 1
        elif loss_at_stop is not None:
            gate["portfolio_stop_exposure"] = round(
                (gate["portfolio_stop_exposure"] or 0.0) + loss_at_stop, 4
            )
        if entry_price and quantity:
            gate["portfolio_equity_basis"] = round(
                (gate["portfolio_equity_basis"] or 0.0) + entry_price * quantity, 4
            )
        if norm["broker_confirmed"]:
            gate["broker_confirmed_count"] += 1

        if blocks or gate["status"] != STATUS_OK:
            gate["blocked_positions"].append(norm)
        else:
            gate["positions"].append(norm)

    gate["monitorable_position_count"] = len(gate["positions"])
    gate["risk_engine_ready"] = (
        gate["status"] == STATUS_OK
        and gate["canonical_holding_count"] > 0
        and gate["missing_stop_count"] == 0
        and gate["unconfirmed_stop_count"] == 0
    )
    if (
        gate["portfolio_stop_exposure"] is not None
        and gate["portfolio_equity_basis"]
    ):
        # Fraction is against COST-BASIS equity (Σ qty × entry) — an honest
        # proxy; true account equity is not known to the repo.
        gate["portfolio_stop_exposure_fraction"] = round(
            gate["portfolio_stop_exposure"] / gate["portfolio_equity_basis"], 6
        )
    if gate["missing_stop_count"]:
        gate["issues"].append(
            f"{gate['missing_stop_count']}/{gate['canonical_holding_count']} "
            "open positions have no stop_loss recorded; they are BLOCKED from "
            "risk monitoring (no stop -> no healthy)"
        )
    if gate["unconfirmed_stop_count"]:
        gate["issues"].append(
            f"{gate['unconfirmed_stop_count']} position(s) carry a stop that "
            "is unconfirmed or directionally invalid — BLOCKED until the "
            "operator confirms (stop_loss_confirmed + stop_loss_confirmed_at "
            f"+ source in {sorted(CONFIRMED_STOP_SOURCES)})"
        )
    if gate["leveraged_without_stop_count"]:
        gate["issues"].append(
            f"CRITICAL: {gate['leveraged_without_stop_count']} LEVERAGED "
            "position(s) carry no usable (confirmed) stop_loss — largest "
            "un-instrumented loss path in the book"
        )
    # Gate-local operational state (the truth surface remains the overall
    # authority; this powers the CLI exit code and operator output).
    if gate["status"] == STATUS_MISSING or gate["status"] == STATUS_INVALID:
        gate["operational_state"] = OP_BROKEN
    elif gate["missing_stop_count"] or gate["unconfirmed_stop_count"]:
        gate["operational_state"] = OP_BLOCKED
    elif gate["freshness_state"] == FRESH_BLOCKED:
        # >3 days without operator re-verification blocks the risk gate
        gate["operational_state"] = OP_BLOCKED
    elif gate["freshness_state"] == FRESH_DEGRADED or gate["status"] == STATUS_STALE:
        gate["operational_state"] = OP_DEGRADED
    elif gate["canonical_holding_count"] > 0 and gate["portfolio_stop_exposure"] is None:
        gate["operational_state"] = OP_BLOCKED  # exposure unknown -> blocked
    else:
        gate["operational_state"] = OP_HEALTHY
    return gate


def canonical_open_position_count(**kwargs: Any) -> int:
    """Open-position count from canonical truth (for capacity gates)."""
    gate = load_holdings_truth_gate(attach_prices=False, **kwargs)
    return int(gate["canonical_holding_count"])


def to_action_engine_position(
    norm: dict[str, Any], *, now_utc: datetime | None = None
) -> dict[str, Any]:
    """Shape a READY canonical position for the action engine's schema.

    Only valid for rows whose ``risk_monitoring`` is READY (stop + fresh
    price present).  Blocked rows must never be adapted — they are surfaced
    as blocked, not monitored.
    """
    if norm.get("risk_monitoring") != MON_READY:
        raise ValueError(
            f"cannot adapt non-READY position {norm.get('ticker')}: "
            f"{norm.get('risk_monitoring')}"
        )
    now = now_utc or datetime.now(timezone.utc)
    entry = float(norm["entry_price"])
    current = float(norm["current_price"])
    opened = _parse_date(norm.get("entry_timestamp"))
    days_held = int((now - opened).days) if opened else 0
    return {
        "ticker": norm["ticker"],
        "entry_price": entry,
        "current_price": current,
        "pnl_pct": round((current / entry - 1.0) * 100.0, 4) if entry else 0.0,
        "stop_loss": float(norm["stop_loss"]),
        "take_profit": (
            float(norm["take_profit"]) if norm.get("take_profit") is not None
            else current * 10.0  # no TP recorded: unreachable sentinel, never triggers
        ),
        "state": "OPEN",
        "position_size": f"LEVERAGE_{norm['leverage']:g}X" if norm["leverage"] > 1 else "UNLEVERAGED",
        "chaos_flag": False,
        "entry_type": "CLEAN",
        "thesis_cluster": str(norm.get("currency") or "UNSPECIFIED"),
        "time_in_trade": f"{days_held}d",
        "priority_score": 0.0,
        "leverage": norm["leverage"],
        "source": SOURCE_NAME,
        "price_as_of": norm.get("price_as_of"),
    }


def build_stop_loss_template(
    *, path: Any = None, now_utc: datetime | None = None
) -> dict[str, Any]:
    """Deterministic stop-loss SUGGESTIONS for every position lacking a
    usable stop.  Suggestions only: every entry ships
    ``requires_operator_confirmation: true`` / ``stop_loss_confirmed: false``
    and the gate stays BLOCKED until the operator flips them with a
    timestamp.  Policy: entry × (1 − 5%) for 1x, entry × (1 − 2.5%) for
    leveraged positions (no ATR series is canonically available; the
    hard-stop percentage policy is used and named)."""
    now = now_utc or datetime.now(timezone.utc)
    gate = load_holdings_truth_gate(path=path, now_utc=now, attach_prices=False)
    entries: list[dict[str, Any]] = []
    for norm in gate["positions"] + gate["blocked_positions"]:
        if norm.get("stop_usable"):
            continue
        entry_price = norm.get("entry_price")
        leverage = norm.get("leverage") or 1.0
        pct = HARD_STOP_PCT_LEVERAGED if leverage > 1 else HARD_STOP_PCT_DEFAULT
        candidate = (
            round(entry_price * (1.0 - pct), 4) if entry_price else None
        )
        entries.append(
            {
                "ticker": norm["ticker"],
                "symbol": norm["symbol"],
                "entry_price": entry_price,
                "quantity": norm.get("quantity"),
                "leverage": leverage,
                "currency": norm.get("currency"),
                "stop_loss_candidate": candidate,
                "candidate_policy": (
                    f"HARD_STOP_{pct:.1%} (leveraged)" if leverage > 1
                    else f"HARD_STOP_{pct:.1%}"
                ),
                "max_loss_at_candidate": (
                    round((entry_price - candidate) * norm["quantity"] * leverage, 4)
                    if entry_price and candidate and norm.get("quantity")
                    else None
                ),
                "stop_loss": candidate,
                "stop_loss_source": "policy_suggested",
                "stop_loss_confirmed": False,
                "stop_loss_confirmed_at": None,
                "operator_confirmation_id": None,
                "operator_confirmation_text": None,
                "risk_acknowledgement": False,
                "leverage_risk_acknowledged": (False if leverage > 1 else None),
                "requires_operator_confirmation": True,
                "operator_instructions": (
                    "Review stop_loss (edit the number if you prefer your own "
                    "level). To activate: set stop_loss_confirmed=true, "
                    "stop_loss_confirmed_at to the current UTC timestamp, "
                    "operator_confirmation_id to any identifier you choose, "
                    "risk_acknowledgement=true, operator_confirmation_text to "
                    f"the EXACT string {OPERATOR_ACK_TEXT!r}"
                    + (" and leverage_risk_acknowledged=true (THIS POSITION "
                       "IS LEVERAGED)" if leverage > 1 else "")
                    + ". Entries missing ANY of these are rejected by "
                    "--apply-confirmed."
                ),
            }
        )
    return {
        "report": "stop_loss_backfill_template",
        "generated_at_utc": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "holdings_run_date": gate["run_date"],
        "policy": {
            "default_hard_stop_pct": HARD_STOP_PCT_DEFAULT,
            "leveraged_hard_stop_pct": HARD_STOP_PCT_LEVERAGED,
            "note": (
                "Suggestions only. Nothing becomes an active stop until the "
                "operator confirms each entry. The risk engine stays BLOCKED "
                "until then."
            ),
        },
        "holdings_confirmed_current": False,
        "holdings_confirmed_current_at": None,
        "holdings_confirmation_instructions": (
            "If (and only if) the positions in verified_current_holdings.json "
            "still exactly match your real book, set "
            "holdings_confirmed_current=true and holdings_confirmed_current_at "
            "to the current UTC timestamp; --apply-confirmed will then refresh "
            "run_date with provenance."
        ),
        "entries": entries,
        **advisory_safety_stamps(),
    }


def validate_stop_template(
    *, template_path: Any = None, holdings_path: Any = None,
    now_utc: datetime | None = None,
) -> dict[str, Any]:
    """Validate every template entry against the strict confirmation contract.

    Rejects (per spec): missing stop, non-numeric stop, directionally invalid
    stop (>= entry for longs), unconfirmed suggestion, missing confirmation
    timestamp, missing/incorrect acknowledgement text, missing confirmation
    id, missing risk acknowledgement, missing leverage acknowledgement on
    leveraged positions, missing/zero leverage on the holding.
    """
    now = now_utc or datetime.now(timezone.utc)
    tpath = Path(template_path) if template_path else STOP_TEMPLATE_PATH
    hpath = Path(
        holdings_path
        if holdings_path is not None
        else os.environ.get(ENV_PATH_OVERRIDE) or HOLDINGS_TRUTH_PATH
    )
    result: dict[str, Any] = {
        "report": "stop_template_validation",
        "checked_at_utc": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "template_path": str(tpath),
        "entries": [],
        "confirmed_valid": 0,
        "unconfirmed": 0,
        "invalid": 0,
        "holdings_refresh_confirmed": False,
        **advisory_safety_stamps(),
    }
    if not tpath.exists():
        result["status"] = "TEMPLATE_MISSING"
        return result
    template = json.loads(tpath.read_text(encoding="utf-8"))
    holdings = {}
    if hpath.exists():
        payload = json.loads(hpath.read_text(encoding="utf-8"))
        holdings = {
            str(p.get("ticker") or "").upper(): p
            for p in payload.get("positions", [])
        }
    for entry in template.get("entries", []):
        ticker = str(entry.get("ticker") or "").upper()
        pos = holdings.get(ticker, {})
        entry_price = _num(pos.get("entry_price")) or _num(entry.get("entry_price"))
        leverage = _num(pos.get("leverage")) or _num(entry.get("leverage"))
        stop = _num(entry.get("stop_loss"))
        reasons: list[str] = []
        if entry.get("stop_loss") is None:
            reasons.append("missing stop_loss")
        elif stop is None:
            reasons.append("stop_loss not numeric")
        elif entry_price is None:
            reasons.append("holding entry_price unknown")
        elif stop >= entry_price:
            reasons.append(
                "directionally invalid: stop >= entry for a long position"
            )
        elif stop <= 0:
            reasons.append("stop must be positive")
        if leverage is None or leverage <= 0:
            reasons.append("leverage missing or zero on the holding")
        confirmed = bool(entry.get("stop_loss_confirmed", False))
        if not confirmed:
            reasons.append("not confirmed (stop_loss_confirmed != true)")
        else:
            if not entry.get("stop_loss_confirmed_at"):
                reasons.append("missing stop_loss_confirmed_at timestamp")
            if not entry.get("operator_confirmation_id"):
                reasons.append("missing operator_confirmation_id")
            if entry.get("operator_confirmation_text") != OPERATOR_ACK_TEXT:
                reasons.append(
                    "operator_confirmation_text must be exactly "
                    + repr(OPERATOR_ACK_TEXT)
                )
            if entry.get("risk_acknowledgement") is not True:
                reasons.append("risk_acknowledgement must be true")
            if (leverage or 1) > 1 and entry.get(
                "leverage_risk_acknowledged"
            ) is not True:
                reasons.append(
                    "leverage_risk_acknowledged must be true for a "
                    "LEVERAGED position"
                )
        verdict = (
            "CONFIRMED_VALID" if confirmed and not reasons
            else "INVALID" if confirmed and reasons
            else "UNCONFIRMED"
        )
        result["entries"].append({
            "ticker": ticker, "verdict": verdict, "reasons": reasons,
            "stop_loss": stop, "leverage": leverage,
        })
        key = {"CONFIRMED_VALID": "confirmed_valid",
               "INVALID": "invalid"}.get(verdict, "unconfirmed")
        result[key] += 1
    result["holdings_refresh_confirmed"] = bool(
        template.get("holdings_confirmed_current") is True
        and template.get("holdings_confirmed_current_at")
    )
    result["status"] = (
        "ALL_CONFIRMED_VALID"
        if result["confirmed_valid"] == len(result["entries"]) and result["entries"]
        else "CONFIRMATION_REQUIRED"
    )
    return result


def write_confirmation_required_artifacts(
    validation: dict[str, Any], *, json_path: Any = None, md_path: Any = None,
) -> dict[str, str]:
    """Persist the operator-facing confirmation-required artifacts.

    Never sets confirmation fields itself — it documents exactly what the
    operator must do, and the risk state stays BLOCKED until they do it.
    """
    jpath = Path(json_path) if json_path else CONFIRMATION_REQUIRED_JSON
    mpath = Path(md_path) if md_path else CONFIRMATION_REQUIRED_MD
    jpath.parent.mkdir(parents=True, exist_ok=True)
    jpath.write_text(
        json.dumps(validation, indent=1, ensure_ascii=False), encoding="utf-8"
    )
    pending = [e for e in validation.get("entries", [])
               if e["verdict"] != "CONFIRMED_VALID"]
    lines = [
        "# STOP-LOSS OPERATOR CONFIRMATION REQUIRED",
        "",
        "_Generated " + str(validation.get("checked_at_utc"))
        + " - the risk engine is **BLOCKED** until every entry below is "
        "confirmed by YOU._",
        "",
        "Template: `" + str(validation.get("template_path")) + "`",
        "",
        "For each entry set ALL of:",
        "",
        "- `stop_loss` (review/edit the suggested level)",
        "- `stop_loss_confirmed: true`",
        "- `stop_loss_confirmed_at`: current UTC timestamp",
        "- `operator_confirmation_id`: any identifier you choose",
        "- `risk_acknowledgement: true`",
        "- `operator_confirmation_text`: exactly `" + OPERATOR_ACK_TEXT + "`",
        "- `leverage_risk_acknowledged: true` on LEVERAGED entries",
        "",
        "Then run:",
        "",
        "```powershell",
        "python scripts/holdings_truth_gate.py --validate-template",
        "python scripts/holdings_truth_gate.py --apply-confirmed --dry-run",
        "python scripts/holdings_truth_gate.py --apply-confirmed --write",
        "```",
        "",
        "## Pending entries",
        "",
    ]
    for e in pending:
        lev = e["leverage"] or 1
        lines.append(
            "- **" + e["ticker"] + "** (leverage " + f"{lev:g}"
            + "x, suggested stop " + str(e["stop_loss"]) + ") - "
            + e["verdict"] + ": "
            + ("; ".join(e["reasons"]) or "awaiting confirmation")
        )
    lines += [
        "",
        "_No stop becomes active until confirmed. Nothing in this repo can",
        "confirm on your behalf._",
        "",
    ]
    mpath.write_text("\n".join(lines), encoding="utf-8")
    return {"json_path": str(jpath), "md_path": str(mpath)}


def show_summary(*, path: Any = None, db_path: Any = None) -> str:
    """Operator-readable one-screen summary of the risk gate."""
    gate = load_holdings_truth_gate(path=path, db_path=db_path)
    lines = [
        "RISK GATE: " + gate["operational_state"]
        + "  (holdings " + gate["status"]
        + ", freshness " + gate["freshness_state"] + ")",
        "holdings: " + str(gate["canonical_holding_count"]) + " open | "
        "monitorable " + str(gate["monitorable_position_count"]) + " | "
        "missing stops " + str(gate["missing_stop_count"]) + " | "
        "unconfirmed " + str(gate["unconfirmed_stop_count"]) + " | "
        "leveraged w/o usable stop "
        + str(gate["leveraged_without_stop_count"]),
        "age: " + str(gate["age_days"]) + " days | exposure: "
        + str(gate["portfolio_stop_exposure"]) + " (fraction "
        + str(gate["portfolio_stop_exposure_fraction"]) + ")",
    ]
    for issue in gate["issues"]:
        lines.append("  ! " + issue)
    for pos in gate["blocked_positions"]:
        extra = (
            " (leverage " + f"{pos['leverage']:g}" + "x)"
            if pos["leverage"] > 1 else ""
        )
        lines.append("  - " + pos["ticker"] + ": "
                     + pos["risk_monitoring"] + extra)
    return "\n".join(lines)


def apply_confirmed_template(
    *,
    template_path: Any = None,
    holdings_path: Any = None,
    now_utc: datetime | None = None,
    write: bool = False,
) -> dict[str, Any]:
    """Apply ONLY operator-confirmed template entries to canonical holdings.

    Fail-closed: entries lacking stop_loss_confirmed=true + a confirmed-at
    timestamp + a numeric, directionally-valid stop are skipped and reported.
    Nothing is invented; provenance is preserved
    (policy_suggested+confirmed -> stop_loss_source='policy_confirmed').
    Dry-run by default; --write persists (a timestamped backup of the
    holdings file is written first).
    """
    now = now_utc or datetime.now(timezone.utc)
    tpath = Path(template_path) if template_path else STOP_TEMPLATE_PATH
    hpath = Path(
        holdings_path
        if holdings_path is not None
        else os.environ.get(ENV_PATH_OVERRIDE) or HOLDINGS_TRUTH_PATH
    )
    result: dict[str, Any] = {
        "report": "apply_confirmed_stops",
        "template_path": str(tpath),
        "holdings_path": str(hpath),
        "write_mode": bool(write),
        "applied": [],
        "skipped": [],
        "run_date_refreshed": False,
        **advisory_safety_stamps(),
    }
    if not tpath.exists():
        result["status"] = "TEMPLATE_MISSING"
        result["detail"] = "run --write-template first"
        return result
    if not hpath.exists():
        result["status"] = "HOLDINGS_TRUTH_MISSING"
        return result
    template = json.loads(tpath.read_text(encoding="utf-8"))
    holdings = json.loads(hpath.read_text(encoding="utf-8"))
    by_ticker = {
        str(p.get("ticker") or "").upper(): p for p in holdings.get("positions", [])
    }
    for entry in template.get("entries", []):
        ticker = str(entry.get("ticker") or "").upper()
        stop = _num(entry.get("stop_loss"))
        confirmed = bool(entry.get("stop_loss_confirmed", False))
        confirmed_at = entry.get("stop_loss_confirmed_at")
        pos = by_ticker.get(ticker)
        why = None
        lev = _num(pos.get("leverage")) if pos else None
        if pos is None:
            why = "ticker not in canonical holdings"
        elif not confirmed:
            why = "not confirmed by operator (stop_loss_confirmed != true)"
        elif not confirmed_at:
            why = "missing stop_loss_confirmed_at timestamp"
        elif not entry.get("operator_confirmation_id"):
            why = "missing operator_confirmation_id"
        elif entry.get("operator_confirmation_text") != OPERATOR_ACK_TEXT:
            why = ("operator_confirmation_text must be exactly "
                   + repr(OPERATOR_ACK_TEXT))
        elif entry.get("risk_acknowledgement") is not True:
            why = "risk_acknowledgement must be true"
        elif stop is None:
            why = "stop_loss not numeric"
        elif not (
            _num(pos.get("entry_price")) and 0 < stop < float(pos["entry_price"])
        ):
            why = "stop not directionally valid for a long position"
        elif lev is None or lev <= 0:
            why = "leverage missing or zero on the holding"
        elif lev > 1 and entry.get("leverage_risk_acknowledged") is not True:
            why = ("leverage_risk_acknowledged must be true for a LEVERAGED "
                   "position")
        if why:
            result["skipped"].append({"ticker": ticker, "reason": why})
            continue
        source_in = str(entry.get("stop_loss_source") or "policy_suggested")
        source_out = (
            "policy_confirmed" if source_in == "policy_suggested"
            else source_in if source_in in CONFIRMED_STOP_SOURCES
            else "operator"
        )
        pos["stop_loss"] = stop
        pos["stop_loss_source"] = source_out
        pos["stop_loss_confirmed"] = True
        pos["stop_loss_confirmed_at"] = confirmed_at
        pos["stop_loss_updated_at"] = confirmed_at
        pos["operator_confirmation_id"] = entry.get("operator_confirmation_id")
        pos["risk_acknowledgement"] = True
        if (lev or 1) > 1:
            pos["leverage_risk_acknowledged"] = True
        result["applied"].append(
            {"ticker": ticker, "stop_loss": stop, "stop_loss_source": source_out}
        )
    if (
        template.get("holdings_confirmed_current") is True
        and template.get("holdings_confirmed_current_at")
    ):
        confirmed_date = str(template["holdings_confirmed_current_at"])[:10]
        holdings["run_date"] = confirmed_date
        holdings["holdings_confirmed_at"] = template[
            "holdings_confirmed_current_at"
        ]
        holdings["holdings_confirmation_source"] = "operator_template"
        holdings["operator_confirmation_id"] = template.get(
            "operator_confirmation_id"
        )
        holdings["run_date_provenance"] = (
            f"operator confirmed holdings current at "
            f"{template['holdings_confirmed_current_at']} via "
            "stop_loss_backfill_template (--apply-confirmed)"
        )
        result["run_date_refreshed"] = True
    result["status"] = "OK" if result["applied"] or result["run_date_refreshed"] else "NOTHING_CONFIRMED"
    if write and result["status"] == "OK":
        HOLDINGS_ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)
        backup = HOLDINGS_ARCHIVE_DIR / (
            "verified_current_holdings_"
            + now.strftime("%Y%m%d_%H%M%S") + ".json"
        )
        backup.write_text(hpath.read_text(encoding="utf-8"), encoding="utf-8")
        hpath.write_text(
            json.dumps(holdings, indent=1, ensure_ascii=False), encoding="utf-8"
        )
        result["backup_path"] = str(backup)
    return result


def _validate_output(gate: dict[str, Any], now: datetime) -> dict[str, Any]:
    age_min = (
        round(gate["age_days"] * 1440.0, 1)
        if isinstance(gate["age_days"], (int, float))
        else None
    )
    return {
        "canonical_holding_count": gate["canonical_holding_count"],
        "active_holding_count": gate["canonical_holding_count"],
        "monitorable_position_count": gate["monitorable_position_count"],
        "missing_stop_count": gate["missing_stop_count"],
        "unconfirmed_stop_count": gate["unconfirmed_stop_count"],
        "leveraged_position_count": gate["leveraged_position_count"],
        "leveraged_without_stop_count": gate["leveraged_without_stop_count"],
        "holdings_age_minutes": age_min,
        "holdings_truth_status": gate["status"],
        "portfolio_stop_exposure": gate["portfolio_stop_exposure"],
        "portfolio_equity_basis": gate["portfolio_equity_basis"],
        "portfolio_stop_exposure_fraction": gate["portfolio_stop_exposure_fraction"],
        "operational_state": gate["operational_state"],
        "risk_engine_ready": gate["risk_engine_ready"],
        "issues": gate["issues"],
        "advisory_status": gate["advisory_status"],
        "execution_gate": gate["execution_gate"],
    }


def main(argv: Sequence[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--path")
    p.add_argument("--db")
    p.add_argument("--max-age-days", type=float, default=DEFAULT_MAX_AGE_DAYS)
    p.add_argument("--validate", action="store_true",
                   help="print the validation summary (default action)")
    p.add_argument("--full", action="store_true", help="print the full gate")
    p.add_argument("--write-template", action="store_true",
                   help="write the stop-loss backfill template (suggestions only)")
    p.add_argument("--validate-template", nargs="?", const="__default__",
                   metavar="PATH",
                   help="validate the confirmation template against the "
                        "strict contract; writes the confirmation-required "
                        "artifacts when anything is pending")
    p.add_argument("--show-summary", action="store_true",
                   help="one-screen operator summary of the risk gate")
    p.add_argument("--dry-run", action="store_true",
                   help="alias: with --apply-confirmed, force dry-run")
    p.add_argument("--apply-confirmed", action="store_true",
                   help="apply operator-CONFIRMED template entries to holdings")
    p.add_argument("--template")
    p.add_argument("--write", action="store_true",
                   help="with --apply-confirmed: persist (dry-run otherwise)")
    args = p.parse_args(argv)
    now = datetime.now(timezone.utc)

    if args.show_summary:
        print(show_summary(path=args.path, db_path=args.db))
        gate = load_holdings_truth_gate(
            path=args.path, db_path=args.db, now_utc=now
        )
        return 0 if gate["operational_state"] in (OP_HEALTHY, OP_DEGRADED) else 1

    if args.validate_template is not None:
        tpl = (
            None if args.validate_template == "__default__"
            else args.validate_template
        )
        validation = validate_stop_template(
            template_path=tpl, holdings_path=args.path, now_utc=now
        )
        if validation["status"] != "ALL_CONFIRMED_VALID":
            paths = write_confirmation_required_artifacts(validation)
            validation["confirmation_required_artifacts"] = paths
        print(json.dumps(validation, indent=2, default=str))
        return 0 if validation["status"] == "ALL_CONFIRMED_VALID" else 1

    if args.write_template:
        template = build_stop_loss_template(path=args.path, now_utc=now)
        target = Path(args.template) if args.template else STOP_TEMPLATE_PATH
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            json.dumps(template, indent=1, ensure_ascii=False), encoding="utf-8"
        )
        print(json.dumps({
            "template_path": str(target),
            "entries": len(template["entries"]),
            "note": template["policy"]["note"],
        }, indent=2))
        return 0

    if args.apply_confirmed:
        result = apply_confirmed_template(
            template_path=args.template, holdings_path=args.path,
            now_utc=now, write=args.write and not args.dry_run,
        )
        print(json.dumps(result, indent=2, default=str))
        return 0 if result["status"] in ("OK", "NOTHING_CONFIRMED") else 1

    gate = load_holdings_truth_gate(
        path=args.path, db_path=args.db, max_age_days=args.max_age_days,
        now_utc=now,
    )
    print(json.dumps(
        gate if args.full else _validate_output(gate, now),
        indent=2, default=str,
    ))
    # Exit semantics: HEALTHY -> 0; DEGRADED -> 0 (non-blocking by design,
    # disclosed in output); BLOCKED/BROKEN -> 1.
    return 0 if gate["operational_state"] in (OP_HEALTHY, OP_DEGRADED) else 1


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
