import type {
  InboxItem,
  InboxListResponse,
  ManualTradeLog,
  TradeReconciliation,
  MoltbookEntry,
  UserReflection,
  AiSummary,
  SignalDetailResponse,
  SourceHealth,
} from '@/types';

const ADVISORY = 'ADVISORY_ONLY';
const HUMAN_ONLY = 'HUMAN_ONLY';

export const MOCK_INBOX_ITEMS: InboxItem[] = [
  {
    event_id: 'FABRIC_BTC',
    ticker: 'BTC',
    signal_state: 'HURACÁN',
    entry_type: 'BREAKOUT',
    priority_score: 0.91,
    observed_at: '2026-05-09T04:12:00Z',
    source_file: 'crypto_signals.jsonl,btc_momentum.jsonl',
    rejection_dimensions: [],
    rejection_reason: '',
    persistence_score: 0.91,
    blocker_pressure_score: 0.12,
    kill_rate_score: 0.08,
    blocker_attribution: 'NONE',
    user_status: 'pending',
    has_reflection: false,
    has_ai_summary: true,
    advisory_status: ADVISORY,
    human_review_required: true,
    execution_mode: HUMAN_ONLY,
    ai_execution_count: 0,
  },
  {
    event_id: 'FABRIC_ETH',
    ticker: 'ETH',
    signal_state: 'AVENTADOR',
    entry_type: 'TREND_CONTINUATION',
    priority_score: 0.78,
    observed_at: '2026-05-09T03:45:00Z',
    source_file: 'eth_signals.jsonl',
    rejection_dimensions: ['VOLUME_LOW'],
    rejection_reason: 'Volume below 30-day average threshold',
    persistence_score: 0.78,
    blocker_pressure_score: 0.31,
    kill_rate_score: 0.22,
    blocker_attribution: 'VOLUME_BLOCKER',
    user_status: 'watchlist',
    has_reflection: true,
    has_ai_summary: true,
    advisory_status: ADVISORY,
    human_review_required: true,
    execution_mode: HUMAN_ONLY,
    ai_execution_count: 0,
  },
  {
    event_id: 'FABRIC_NVDA',
    ticker: 'NVDA',
    signal_state: 'MURCIÉLAGO',
    entry_type: 'MOMENTUM_SURGE',
    priority_score: 0.85,
    observed_at: '2026-05-09T02:30:00Z',
    source_file: 'equity_signals.jsonl,nvda_fundamentals.jsonl',
    rejection_dimensions: [],
    rejection_reason: '',
    persistence_score: 0.85,
    blocker_pressure_score: 0.18,
    kill_rate_score: 0.14,
    blocker_attribution: 'NONE',
    user_status: 'human_review',
    has_reflection: true,
    has_ai_summary: false,
    advisory_status: ADVISORY,
    human_review_required: true,
    execution_mode: HUMAN_ONLY,
    ai_execution_count: 0,
  },
  {
    event_id: 'FABRIC_TSLA',
    ticker: 'TSLA',
    signal_state: 'DIABLO',
    entry_type: 'REVERSAL_CANDIDATE',
    priority_score: 0.72,
    observed_at: '2026-05-09T01:15:00Z',
    source_file: 'equity_signals.jsonl',
    rejection_dimensions: ['REGIME_MISMATCH', 'VOLATILITY_HIGH'],
    rejection_reason: 'Current regime does not support this entry type',
    persistence_score: 0.72,
    blocker_pressure_score: 0.64,
    kill_rate_score: 0.51,
    blocker_attribution: 'REGIME_BLOCKER',
    user_status: 'rejected',
    has_reflection: true,
    has_ai_summary: true,
    advisory_status: ADVISORY,
    human_review_required: true,
    execution_mode: HUMAN_ONLY,
    ai_execution_count: 0,
  },
  {
    event_id: 'FABRIC_AAPL',
    ticker: 'AAPL',
    signal_state: 'GALLARDO',
    entry_type: 'ACCUMULATION',
    priority_score: 0.61,
    observed_at: '2026-05-09T00:00:00Z',
    source_file: 'equity_signals.jsonl,macro_overlay.jsonl',
    rejection_dimensions: ['MOMENTUM_WEAK'],
    rejection_reason: 'Momentum score below entry threshold',
    persistence_score: 0.61,
    blocker_pressure_score: 0.42,
    kill_rate_score: 0.29,
    blocker_attribution: 'MOMENTUM_BLOCKER',
    user_status: 'pending',
    has_reflection: false,
    has_ai_summary: false,
    advisory_status: ADVISORY,
    human_review_required: true,
    execution_mode: HUMAN_ONLY,
    ai_execution_count: 0,
  },
  {
    event_id: 'FABRIC_SOL',
    ticker: 'SOL',
    signal_state: 'ISLERO',
    entry_type: 'RANGE_BREAKOUT',
    priority_score: 0.55,
    observed_at: '2026-05-08T22:10:00Z',
    source_file: 'crypto_signals.jsonl',
    rejection_dimensions: ['LIQUIDITY_CONCERN'],
    rejection_reason: 'Liquidity depth insufficient at target level',
    persistence_score: 0.55,
    blocker_pressure_score: 0.55,
    kill_rate_score: 0.38,
    blocker_attribution: 'LIQUIDITY_BLOCKER',
    user_status: 'watchlist',
    has_reflection: false,
    has_ai_summary: false,
    advisory_status: ADVISORY,
    human_review_required: true,
    execution_mode: HUMAN_ONLY,
    ai_execution_count: 0,
  },
  {
    event_id: 'FABRIC_SPY',
    ticker: 'SPY',
    signal_state: 'MIURA',
    entry_type: 'MACRO_HEDGE',
    priority_score: 0.44,
    observed_at: '2026-05-08T20:00:00Z',
    source_file: 'macro_overlay.jsonl',
    rejection_dimensions: ['CORRELATION_HIGH', 'REGIME_NEUTRAL'],
    rejection_reason: 'Macro regime neutral; signal strength insufficient',
    persistence_score: 0.44,
    blocker_pressure_score: 0.71,
    kill_rate_score: 0.62,
    blocker_attribution: 'REGIME_BLOCKER',
    user_status: 'rejected',
    has_reflection: false,
    has_ai_summary: false,
    advisory_status: ADVISORY,
    human_review_required: true,
    execution_mode: HUMAN_ONLY,
    ai_execution_count: 0,
  },
  {
    event_id: 'FABRIC_AMZN',
    ticker: 'AMZN',
    signal_state: 'AVENTADOR',
    entry_type: 'EARNINGS_SETUP',
    priority_score: 0.80,
    observed_at: '2026-05-08T18:30:00Z',
    source_file: 'equity_signals.jsonl,earnings_calendar.jsonl',
    rejection_dimensions: [],
    rejection_reason: '',
    persistence_score: 0.80,
    blocker_pressure_score: 0.22,
    kill_rate_score: 0.17,
    blocker_attribution: 'NONE',
    user_status: 'reconciled',
    has_reflection: true,
    has_ai_summary: true,
    advisory_status: ADVISORY,
    human_review_required: true,
    execution_mode: HUMAN_ONLY,
    ai_execution_count: 0,
  },
];

export const MOCK_INBOX_RESPONSE: InboxListResponse = {
  operation: 'list_inbox_items',
  item_count: MOCK_INBOX_ITEMS.length,
  items: MOCK_INBOX_ITEMS,
  fabric_bull_state: 'AVENTADOR',
  fabric_stats: {
    total_tickers: 8,
    total_signals: 47,
    source_files: 6,
  },
  advisory_status: ADVISORY,
  human_review_required: true,
  execution_mode: HUMAN_ONLY,
  ai_execution_count: 0,
  generated_at: '2026-05-09T04:30:00Z',
};

export const MOCK_REFLECTIONS: UserReflection[] = [
  {
    reflection_id: 'REF_a1b2c3d4e5',
    event_id: 'FABRIC_ETH',
    author: 'human',
    conviction_level: 'MODERATE',
    reflection_text:
      'Volume blocker is a concern but the trend structure looks clean. Watching for volume to recover above the 20-day MA before acting.',
    reflected_at: '2026-05-09T03:50:00Z',
    advisory_status: ADVISORY,
    human_review_required: true,
  },
  {
    reflection_id: 'REF_f6g7h8i9j0',
    event_id: 'FABRIC_NVDA',
    author: 'human',
    conviction_level: 'HIGH',
    reflection_text:
      'NVDA momentum surge aligns with AI infrastructure narrative. Entry window looks compelling but I want to see another day of confirmation.',
    reflected_at: '2026-05-09T02:35:00Z',
    advisory_status: ADVISORY,
    human_review_required: true,
  },
  {
    reflection_id: 'REF_k1l2m3n4o5',
    event_id: 'FABRIC_TSLA',
    author: 'human',
    conviction_level: 'LOW',
    reflection_text:
      'Rejecting this one. The regime mismatch is too significant and volatility is too high relative to expected reward. Will revisit if conditions normalize.',
    reflected_at: '2026-05-09T01:20:00Z',
    advisory_status: ADVISORY,
    human_review_required: true,
  },
];

export const MOCK_AI_SUMMARIES: AiSummary[] = [
  {
    summary_id: 'SUM_p6q7r8s9t0',
    event_id: 'FABRIC_BTC',
    model_label: 'AI_ADVISORY',
    summary_text:
      'BTC shows strong persistence (0.91) with minimal blocker pressure (0.12). Historical pattern analysis suggests this entry type has a 67% follow-through rate in similar market conditions. Note: this is observational context only, not a recommendation.',
    summarized_at: '2026-05-09T04:15:00Z',
    advisory_status: ADVISORY,
    human_review_required: true,
    advisory_note:
      'AI-generated discussion context only — not a trade recommendation and does not authorize any execution.',
  },
  {
    summary_id: 'SUM_u1v2w3x4y5',
    event_id: 'FABRIC_ETH',
    model_label: 'AI_ADVISORY',
    summary_text:
      'ETH trend continuation signal is partially blocked by volume weakness. The rejection dimension VOLUME_LOW has historically been a meaningful friction factor. Advisory context only.',
    summarized_at: '2026-05-09T03:48:00Z',
    advisory_status: ADVISORY,
    human_review_required: true,
    advisory_note:
      'AI-generated discussion context only — not a trade recommendation and does not authorize any execution.',
  },
];

export const MOCK_MANUAL_TRADES: ManualTradeLog[] = [
  {
    trade_id: 'MT_a1b2c3d4e5f6',
    event_id: 'FABRIC_AMZN',
    ticker: 'AMZN',
    side: 'BUY',
    quantity: 10,
    price: 182.5,
    executed_at: '2026-05-08T19:00:00Z',
    thesis: 'Earnings setup with strong persistence score; entered manually after human review.',
    notes: 'Scaled in at market open. Watching 185 as first target.',
    logged_by: 'human',
    execution_mode: HUMAN_ONLY,
    ai_execution_count: 0,
    advisory_status: ADVISORY,
    human_review_required: true,
    broker_order_id: 'NONE',
    broker_api_called: false,
  },
];

export const MOCK_RECONCILIATIONS: TradeReconciliation[] = [
  {
    reconciliation_id: 'REC_z9y8x7w6v5u4',
    trade_id: 'MT_a1b2c3d4e5f6',
    event_id: 'FABRIC_AMZN',
    reconciled_at: '2026-05-09T10:00:00Z',
    actual_fill_price: 183.2,
    actual_quantity: 10,
    outcome_notes:
      'Filled slightly above log price. Position closed at 189.4 for +3.8% gain. Signal thesis validated.',
    pnl_estimate: 69.0,
    outcome_status: 'WIN',
    execution_mode: HUMAN_ONLY,
    ai_execution_count: 0,
    advisory_status: ADVISORY,
    human_review_required: true,
  },
];

export const MOCK_MOLTBOOK_ENTRIES: MoltbookEntry[] = [
  {
    entry_id: 'MB_aa1bb2cc3dd4',
    event_id: 'FABRIC_TSLA',
    ticker: 'TSLA',
    original_signal_thesis:
      'TSLA reversal candidate with DIABLO state and 0.72 priority score.',
    ai_interpretation:
      'Contextual note: reversal candidates in high-volatility regimes historically have lower follow-through rates. Blocker pressure at 0.64 is significant.',
    user_reflection:
      'I initially considered this trade but the regime mismatch concerned me. The VOLATILITY_HIGH flag was a clear warning.',
    final_human_decision: 'REJECTED — did not trade',
    manual_trade_log_id: '',
    outcome:
      'TSLA dropped 8% over next 3 sessions. Rejection was correct.',
    mistake_type: 'bad_signal_correct_rejection',
    lesson_learned:
      'REGIME_MISMATCH + VOLATILITY_HIGH = high-conviction rejection. Trust the blocker stack when multiple dimensions align.',
    bias_detected: 'FOMO',
    recalibration_note:
      'When 2+ rejection dimensions are active and blocker pressure > 0.5, require extraordinary evidence before overriding.',
    future_rule_update:
      'Add rule: If blocker_pressure_score > 0.5 AND len(rejection_dimensions) >= 2, auto-flag for mandatory human_review before watchlist.',
    logged_at: '2026-05-09T02:00:00Z',
    advisory_status: ADVISORY,
    human_review_required: true,
    execution_mode: HUMAN_ONLY,
    ai_execution_count: 0,
  },
  {
    entry_id: 'MB_ee5ff6gg7hh8',
    event_id: 'FABRIC_BTC',
    ticker: 'BTC',
    original_signal_thesis:
      'BTC HURACÁN state with 0.91 persistence — strongest signal in current window.',
    ai_interpretation:
      'High persistence, minimal blockers. Pattern historically associated with sustained momentum. Advisory context only.',
    user_reflection:
      'Spent too long deliberating. Missed the initial breakout window due to hesitation.',
    final_human_decision: 'Entered late — partial position only',
    manual_trade_log_id: '',
    outcome: 'Partial position captured 40% of the move. Left significant upside.',
    mistake_type: 'late_entry',
    lesson_learned:
      'When HURACÁN state + blocker_pressure < 0.2 + kill_rate < 0.15, act within one session window.',
    bias_detected: 'ANALYSIS_PARALYSIS',
    recalibration_note:
      'Set a maximum deliberation window for top-tier signals. Decision must be made within defined timeframe.',
    future_rule_update:
      'For signals with priority_score > 0.85 and no active blockers, set 4-hour review deadline.',
    logged_at: '2026-05-08T15:00:00Z',
    advisory_status: ADVISORY,
    human_review_required: true,
    execution_mode: HUMAN_ONLY,
    ai_execution_count: 0,
  },
];

export const MOCK_SOURCE_HEALTH: SourceHealth[] = [
  { source_file: 'crypto_signals.jsonl', ticker_count: 12, last_seen: '2026-05-09T04:10:00Z', status: 'active' },
  { source_file: 'equity_signals.jsonl', ticker_count: 31, last_seen: '2026-05-09T04:05:00Z', status: 'active' },
  { source_file: 'macro_overlay.jsonl', ticker_count: 8, last_seen: '2026-05-09T03:50:00Z', status: 'active' },
  { source_file: 'btc_momentum.jsonl', ticker_count: 1, last_seen: '2026-05-09T04:12:00Z', status: 'active' },
  { source_file: 'nvda_fundamentals.jsonl', ticker_count: 1, last_seen: '2026-05-09T02:28:00Z', status: 'active' },
  { source_file: 'earnings_calendar.jsonl', ticker_count: 5, last_seen: '2026-05-08T20:00:00Z', status: 'stale' },
];

export function getMockSignalDetail(eventId: string): SignalDetailResponse {
  const signal = MOCK_INBOX_ITEMS.find((i) => i.event_id === eventId) ?? MOCK_INBOX_ITEMS[0];
  return {
    operation: 'get_signal_detail',
    event_id: eventId,
    signal,
    ticker_summary: {
      ticker: signal.ticker,
      latest_signal_state: signal.signal_state,
      persistence_score: signal.persistence_score,
      blocker_pressure_score: signal.blocker_pressure_score,
      kill_rate_score: signal.kill_rate_score,
      latest_blocker: signal.blocker_attribution,
      source_files: signal.source_file.split(','),
    },
    reflections: MOCK_REFLECTIONS.filter((r) => r.event_id === eventId),
    ai_summaries: MOCK_AI_SUMMARIES.filter((s) => s.event_id === eventId),
    manual_trades: MOCK_MANUAL_TRADES.filter((t) => t.event_id === eventId),
    advisory_status: ADVISORY,
    human_review_required: true,
    execution_mode: HUMAN_ONLY,
    ai_execution_count: 0,
    generated_at: '2026-05-09T04:30:00Z',
  };
}
